In [1]:
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 
plt.rcParams['figure.figsize'] = 10, 8

from sklearn.preprocessing import StandardScaler
from sklearn import cross_validation
from sklearn.cross_validation import StratifiedKFold, KFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.ensemble import ExtraTreesClassifier

In [2]:
def binary_class(row):
    if row < 0.00:
        return 0
    else:
        return 1

In [3]:
def update_return_class(row, neg_cutoff, pos_cutoff):
    if row <= neg_cutoff:
        return 0
    elif row > neg_cutoff and row < pos_cutoff:
        return 1
    elif row >= pos_cutoff:
        return 2

In [5]:
data = pd.read_csv('data/price_data_68.csv')
data1 = pd.read_csv('data/price_data_1.csv')
data2 = pd.read_csv('data/price_data_2.csv')
data3 = pd.read_csv('data/price_data_3.csv')
data4 = pd.read_csv('data/price_data_4.csv')
data5 = pd.read_csv('data/price_data_5.csv')
data6 = pd.read_csv('data/price_data_6.csv')
data7 = pd.read_csv('data/price_data_7.csv')
data8 = pd.read_csv('data/price_data_8.csv')

del data['Date']
del data1['Date']
del data2['Date']
del data3['Date']
del data4['Date']
del data5['Date']
del data6['Date']
del data7['Date']
del data8['Date']

In [6]:
# Process only the main training data
X = data.loc[:,'F1':'F68']
y5 = data.loc[:,'RET5']
y10 = data.loc[:,'RET10']
y15 = data.loc[:,'RET15']
y20 = data.loc[:,'RET20']
y25 = data.loc[:,'RET25']
y30 = data.loc[:,'RET30']

y5.columns = ['RET']
y10.columns = ['RET']
y15.columns = ['RET']
y20.columns = ['RET']
y25.columns = ['RET']
y30.columns = ['RET']

In [7]:
y5_b = pd.Series(index=y5.index)
y10_b = pd.Series(index=y5.index)
y15_b = pd.Series(index=y5.index)
y20_b = pd.Series(index=y5.index)
y25_b = pd.Series(index=y5.index)
y30_b = pd.Series(index=y5.index)

y5_b = y5.apply(binary_class)
y10_b = y10.apply(binary_class)
y15_b = y15.apply(binary_class)
y20_b = y20.apply(binary_class)
y25_b = y25.apply(binary_class)
y30_b = y30.apply(binary_class)


y5_t = pd.Series(index=y5.index)
y10_t = pd.Series(index=y5.index)
y15_t = pd.Series(index=y5.index)
y20_t = pd.Series(index=y5.index)
y25_t = pd.Series(index=y5.index)
y30_t = pd.Series(index=y5.index)

y5_t = y5.apply(update_return_class, args=(-0.02, 0.02))
y10_t = y10.apply(update_return_class, args=(-0.03, 0.03))
y15_t = y15.apply(update_return_class, args=(-0.05, 0.05))
y20_t = y20.apply(update_return_class, args=(-0.05, 0.05))
y25_t = y25.apply(update_return_class, args=(-0.05, 0.07))
y30_t = y30.apply(update_return_class, args=(-0.05, 0.08))

In [8]:
X = data.loc[:,['F19','F35','F36','F37','F38','F39','F40','F41','F46','F47','F52','F54','F55','F56','F57','F58','F59','F64','F66','F67']]

In [12]:
et = ExtraTreesClassifier(n_estimators=250, max_depth=25)
stdsc = StandardScaler()

validation_size = 0.20
seed = 7

In [23]:
X5b_train, X5b_test, y5b_train, y5b_test = cross_validation.train_test_split(X, y5_b, test_size=validation_size, 
                                                                                 random_state=seed)
X10b_train, X10b_test, y10b_train, y10b_test = cross_validation.train_test_split(X, y10_b, test_size=validation_size, 
                                                                                 random_state=seed)
X15b_train, X15b_test, y15b_train, y15b_test = cross_validation.train_test_split(X, y15_b, test_size=validation_size, 
                                                                                 random_state=seed)
X20b_train, X20b_test, y20b_train, y20b_test = cross_validation.train_test_split(X, y20_b, test_size=validation_size, 
                                                                                 random_state=seed)
X25b_train, X25b_test, y25b_train, y25b_test = cross_validation.train_test_split(X, y25_b, test_size=validation_size, 
                                                                                 random_state=seed)
X30b_train, X30b_test, y30b_train, y30b_test = cross_validation.train_test_split(X, y30_b, test_size=validation_size, 
                                                                                 random_state=seed)

X5t_train, X5t_test, y5t_train, y5t_test = cross_validation.train_test_split(X, y5_t, test_size=validation_size, 
                                                                                 random_state=seed)
X10t_train, X10t_test, y10t_train, y10t_test = cross_validation.train_test_split(X, y10_t, test_size=validation_size, 
                                                                                 random_state=seed)
X15t_train, X15t_test, y15t_train, y15t_test = cross_validation.train_test_split(X, y15_t, test_size=validation_size, 
                                                                                 random_state=seed)
X20t_train, X20t_test, y20t_train, y20t_test = cross_validation.train_test_split(X, y20_t, test_size=validation_size, 
                                                                                 random_state=seed)
X25t_train, X25t_test, y25t_train, y25t_test = cross_validation.train_test_split(X, y25_t, test_size=validation_size, 
                                                                                 random_state=seed)
X30t_train, X30t_test, y30t_train, y30t_test = cross_validation.train_test_split(X, y30_t, test_size=validation_size, 
                                                                                 random_state=seed)

In [41]:
def prediction_model(X_train, X_test, y_train, y_test, scale_model, predict_model):
    X_train_std = scale_model.transform(X_train)
    X_test_std = scale_model.transform(X_test)

    predict_model.fit(X_train_std, y_train)
    predict = predict_model.predict(X_test_std)

    print(accuracy_score(y_test, predict))
    print(confusion_matrix(y_test, predict))
    print(classification_report(y_test, predict))
    
    return predict_model

In [45]:
# Scale data only once and re-use the scaling transformer for other models
_ = stdsc.fit_transform(X5b_train)

data_split = {
    '5b':{
        'descr':'5-day Binary',
        'X_train':X5b_train,
        'X_test':X5b_test,
        'y_train':y5b_train,
        'y_test':y5b_test
    },
    '10b':{
        'descr':'10-day Binary',
        'X_train':X10b_train,
        'X_test':X10b_test,
        'y_train':y10b_train,
        'y_test':y10b_test
    },
    '15b':{
        'descr':'15-day Binary',
        'X_train':X15b_train,
        'X_test':X15b_test,
        'y_train':y15b_train,
        'y_test':y15b_test
    },
    '20b':{
        'descr':'20-day Binary',
        'X_train':X20b_train,
        'X_test':X20b_test,
        'y_train':y20b_train,
        'y_test':y20b_test
    },
    '25b':{
        'descr':'25-day Binary',
        'X_train':X25b_train,
        'X_test':X25b_test,
        'y_train':y25b_train,
        'y_test':y25b_test
    },
    '30b':{
        'descr':'30-day Binary',
        'X_train':X30b_train,
        'X_test':X30b_test,
        'y_train':y30b_train,
        'y_test':y30b_test
    },
    '5t':{
        'descr':'5-day Trinary',
        'X_train':X5b_train,
        'X_test':X5b_test,
        'y_train':y5b_train,
        'y_test':y5b_test
    },
    '10t':{
        'descr':'10-day Trinary',
        'X_train':X10t_train,
        'X_test':X10t_test,
        'y_train':y10t_train,
        'y_test':y10t_test
    },
    '15t':{
        'descr':'15-day Trinary',
        'X_train':X15t_train,
        'X_test':X15t_test,
        'y_train':y15t_train,
        'y_test':y15t_test
    },
    '20t':{
        'descr':'20-day Trinary',
        'X_train':X20t_train,
        'X_test':X20t_test,
        'y_train':y20t_train,
        'y_test':y20t_test
    },
    '25t':{
        'descr':'25-day Trinary',
        'X_train':X25t_train,
        'X_test':X25t_test,
        'y_train':y25t_train,
        'y_test':y25t_test
    },
    '30t':{
        'descr':'30-day Trinary',
        'X_train':X30t_train,
        'X_test':X30t_test,
        'y_train':y30t_train,
        'y_test':y30t_test
    }
}

models = {}

for key in data_split:
    print('-------------------------------------------------------------')
    print('Prediction for: %s ' % data_split[str(key)]['descr'])
    predict = prediction_model(data_split[key]['X_train'], data_split[key]['X_test'], 
                                data_split[key]['y_train'], data_split[key]['y_test'], 
                                stdsc, et)
    models[key] = predict

-------------------------------------------------------------
Prediction for: 10-day Binary 
0.873485868102
[[280  55]
 [ 39 369]]
             precision    recall  f1-score   support

          0       0.88      0.84      0.86       335
          1       0.87      0.90      0.89       408

avg / total       0.87      0.87      0.87       743

-------------------------------------------------------------
Prediction for: 30-day Trinary 
0.893674293405
[[202  23   0]
 [ 22 190  18]
 [  0  16 272]]
             precision    recall  f1-score   support

          0       0.90      0.90      0.90       225
          1       0.83      0.83      0.83       230
          2       0.94      0.94      0.94       288

avg / total       0.89      0.89      0.89       743

-------------------------------------------------------------
Prediction for: 15-day Trinary 
0.829071332436
[[163  27   1]
 [ 25 230  35]
 [  2  37 223]]
             precision    recall  f1-score   support

          0       0.86

In [46]:
for key in models:
    print('Model for: %s' % key)
    print(models[key])

Model for: 10b
ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=25, max_features='auto', max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=250, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)
Model for: 30t
ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=25, max_features='auto', max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=250, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)
Model for: 15t
ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=25, max_features='auto', max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=250, n_jobs=1,
           oob